/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearbookRouteImport } from './routes/yearbook'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoveRouteImport } from './routes/love'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FromPragsRouteImport } from './routes/from-prags'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsSlugRouteImport } from './routes/friends.$slug'
import { Route as AdminFreshersRouteImport } from './routes/admin.freshers'
import { Route as AdminAvatarsRouteImport } from './routes/admin.avatars'

const YearbookRoute = YearbookRouteImport.update({
  id: '/yearbook',
  path: '/yearbook',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FromPragsRoute = FromPragsRouteImport.update({
  id: '/from-prags',
  path: '/from-prags',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsSlugRoute = FriendsSlugRouteImport.update({
  id: '/friends/$slug',
  path: '/friends/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFreshersRoute = AdminFreshersRouteImport.update({
  id: '/admin/freshers',
  path: '/admin/freshers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvatarsRoute = AdminAvatarsRouteImport.update({
  id: '/admin/avatars',
  path: '/admin/avatars',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/from-prags': typeof FromPragsRoute
  '/gallery': typeof GalleryRoute
  '/letter': typeof LetterRoute
  '/love': typeof LoveRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/yearbook': typeof YearbookRoute
  '/admin/avatars': typeof AdminAvatarsRoute
  '/admin/freshers': typeof AdminFreshersRoute
  '/friends/$slug': typeof FriendsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/from-prags': typeof FromPragsRoute
  '/gallery': typeof GalleryRoute
  '/letter': typeof LetterRoute
  '/love': typeof LoveRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/yearbook': typeof YearbookRoute
  '/admin/avatars': typeof AdminAvatarsRoute
  '/admin/freshers': typeof AdminFreshersRoute
  '/friends/$slug': typeof FriendsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/from-prags': typeof FromPragsRoute
  '/gallery': typeof GalleryRoute
  '/letter': typeof LetterRoute
  '/love': typeof LoveRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/yearbook': typeof YearbookRoute
  '/admin/avatars': typeof AdminAvatarsRoute
  '/admin/freshers': typeof AdminFreshersRoute
  '/friends/$slug': typeof FriendsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/from-prags'
    | '/gallery'
    | '/letter'
    | '/love'
    | '/quiz'
    | '/sitemap.xml'
    | '/timeline'
    | '/yearbook'
    | '/admin/avatars'
    | '/admin/freshers'
    | '/friends/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/from-prags'
    | '/gallery'
    | '/letter'
    | '/love'
    | '/quiz'
    | '/sitemap.xml'
    | '/timeline'
    | '/yearbook'
    | '/admin/avatars'
    | '/admin/freshers'
    | '/friends/$slug'
  id:
    | '__root__'
    | '/'
    | '/from-prags'
    | '/gallery'
    | '/letter'
    | '/love'
    | '/quiz'
    | '/sitemap.xml'
    | '/timeline'
    | '/yearbook'
    | '/admin/avatars'
    | '/admin/freshers'
    | '/friends/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FromPragsRoute: typeof FromPragsRoute
  GalleryRoute: typeof GalleryRoute
  LetterRoute: typeof LetterRoute
  LoveRoute: typeof LoveRoute
  QuizRoute: typeof QuizRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  YearbookRoute: typeof YearbookRoute
  AdminAvatarsRoute: typeof AdminAvatarsRoute
  AdminFreshersRoute: typeof AdminFreshersRoute
  FriendsSlugRoute: typeof FriendsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yearbook': {
      id: '/yearbook'
      path: '/yearbook'
      fullPath: '/yearbook'
      preLoaderRoute: typeof YearbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from-prags': {
      id: '/from-prags'
      path: '/from-prags'
      fullPath: '/from-prags'
      preLoaderRoute: typeof FromPragsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$slug': {
      id: '/friends/$slug'
      path: '/friends/$slug'
      fullPath: '/friends/$slug'
      preLoaderRoute: typeof FriendsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/freshers': {
      id: '/admin/freshers'
      path: '/admin/freshers'
      fullPath: '/admin/freshers'
      preLoaderRoute: typeof AdminFreshersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avatars': {
      id: '/admin/avatars'
      path: '/admin/avatars'
      fullPath: '/admin/avatars'
      preLoaderRoute: typeof AdminAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FromPragsRoute: FromPragsRoute,
  GalleryRoute: GalleryRoute,
  LetterRoute: LetterRoute,
  LoveRoute: LoveRoute,
  QuizRoute: QuizRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimelineRoute: TimelineRoute,
  YearbookRoute: YearbookRoute,
  AdminAvatarsRoute: AdminAvatarsRoute,
  AdminFreshersRoute: AdminFreshersRoute,
  FriendsSlugRoute: FriendsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
